"""a

Revision ID: 983161820f36
Revises: c421ddb36dd8
Create Date: 2024-01-11 16:13:54.884874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983161820f36'
down_revision = 'c421ddb36dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apt_number', sa.Integer(), nullable=True))
        batch_op.drop_column('number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.INTEGER(), nullable=True))
        batch_op.drop_column('apt_number')

    # ### end Alembic commands ###
